#!/bin/bash

set -eu

URL=local.hoctranshop.vn

echo "===> Cloning the source code of Eccube4..."
git clone git@github.com:EC-CUBE/ec-cube.git eccube

cp .env.dev eccube/.env
cp ./scripts/create_db.sql eccube/dockerbuild/create_db.sql
cp docker-compose.yml eccube/docker-compose.yml
rm -rf eccube/.github
rm -rf eccube/.git

# Firing up Docker containers
echo "===> Starting up Docker containers..."
docker-compose stop
docker-compose -f eccube/docker-compose.yml up -d
echo "===> Docker containers started"

echo "===> Restart Docker containers..."
docker-compose -f eccube/docker-compose.yml restart

find . -name "*.DS_Store" -type f -delete

# Setting Hosts
echo "===> Add domain to hosts file"
sudo -- sh -c "echo '0.0.0.0:8080 ${URL}' >> /etc/hosts"

# Open Site in browser
open https://"${URL}"

echo "===> Local setup successfully finished!"
